#!/bin/bash
hostname=$(hostname -s)
user=$(whoami)
cmd=$(cp -rf /home/module/modules.conf /etc/modules-load.d/modules.conf)
cmd=$(chmod 777 /etc/modules-load.d/modules.conf)
cmd=$(modprobe overlay)
cmd=$(modprobe br_netfilter)
cmd=$(cp -rf /home/module/k8s.conf /etc/sysctl.d/k8s.conf)
cmd=$(chmod 411 /etc/sysctl.d/k8s.conf)
cmd=$(sudo sysctl --system)
cmd=$(apt-get update)
cmd=$(apt-get install -y ca-certificates curl gnupg lsb-release)
cmd=$(mkdir -m 0755 -p /etc/apt/keyrings)
cmd=$(curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg)
cmd=$(mkdir -m 0755 -p /etc/apt/sources.list.d)
cmd=$(echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null)
cmd=$(apt-get update)
cmd=$(apt-get install -y containerd.io)
cmd=$(cp -rf /home/module/config.toml /etc/containerd/config.toml)
cmd=$(chmod 411 /etc/containerd/config.toml)
cmd=$(systemctl restart containerd)
cmd=$(systemctl enable containerd)