#For referrence: https://docs.ansible.com/ansible/latest/collections/ansible/builtin/shell_module.html
---
- hosts: all
  become: true

  tasks:
    #install apt package manager
    - name: Install aptitude
      become: yes
      become_user: root
      apt:
        name: aptitude
        state: latest
        update_cache: true

    - name: Copying script to Nodes
      become: true 
      copy:
        src: script
        dest: /home/
        owner: root
        group: root
        mode: 0755

    - name: Copying module to Nodes
      become: true 
      copy:
        src: module
        dest: /home/
        owner: root
        group: root
        mode: 0755

    - name: Run setup script
      become: true
      become_user: root
      ansible.builtin.shell: /bin/sh /home/script/setup.sh

    - name: Run option1 script
      become: true
      become_user: root
      ansible.builtin.shell: /bin/sh /home/script/option1.sh

    - name: Run option2 script
      become: true
      become_user: root
      ansible.builtin.shell: /bin/sh /home/script/option2.sh